apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

resources:
  # dashboard
  - dashboard/dash-node.yaml
  - dashboard/dash-redis.yaml
  - dashboard/dash-tempo.yaml
  - dashboard/dash-backend.yaml
  # alert rules
  - alert/backend-alert-rule.yaml

helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: 79.6.1
    releaseName: kube-prometheus-stack
    valuesFile: values.yaml
    includeCRDs: true