apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: collector

helmCharts:
  - name: alloy
    repo: https://grafana.github.io/helm-charts
    version: 1.5.2
    releaseName: alloy
    valuesFile: values.yaml
    includeCRDs: true