apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

helmCharts:
  - name: aws-node-termination-handler
    repo: https://aws.github.io/eks-charts
    version: 0.21.0
    releaseName: aws-node-termination-handler
    valuesFile: values.yaml
    includeCRDs: true

resources:
  - secrets/sealed-nth.yaml
  - podmonitor.yaml