apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tracing

helmCharts:
  - name: tempo
    repo: https://grafana.github.io/helm-charts
    version: 1.24.1
    releaseName: tempo
    valuesFile: values.yaml
    includeCRDs: true